### ISSUE TITLE
根据规范不应该使用彩色图标

### ISSUE THREAD

**Issue by heartacker** [jks-liu/WPL-s#1]
![image](https://user-images.githubusercontent.com/1876302/132445916-e6c56d80-3bc8-41a5-9419-840039a2d487.png)

![image](https://user-images.githubusercontent.com/1876302/132445959-6507d8b7-d0af-4873-8fe1-9b8c459a72ef.png)

**Comment by jks-liu** [comment]
谢谢你的反馈。
我对 VS Code 扩展的开发还不是很熟，可以贴一个规范的具体地址吗。

**Comment by heartacker** [comment]
https://code.visualstudio.com/api/references/extension-guidelines#editor-actions

**Comment by heartacker** [comment]
这个会改吗？有点扎眼睛

**Comment by jks-liu** [comment]
近期会改

**Comment by jks-liu** [comment]
已修改
